---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  requiresafe:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/
