measurements:
  - url: '/dhwCircuits/dhw1/actualTemp'
  - url: '/dhwCircuits/dhw1/charge'
  - url: '/dhwCircuits/dhw1/currentSetpoint'
  - url: '/dhwCircuits/dhw1/chargeDuration'
  - url: '/heatSources/actualSupplyTemperature'
  - url: '/heatSources/applianceSupplyTemperature'
  - url: '/heatSources/actualModulation'
  - url: '/heatSources/energyMonitoring/consumption'
  - url: '/heatingCircuits/hc2/actualSupplyTemperature'
  - url: '/heatingCircuits/hc2/currentRoomSetpoint'
  - url: '/heatingCircuits/hc2/pumpModulation'
  - url: '/heatingCircuits/hc2/roomtemperature'
  - url: '/heatingCircuits/hc3/actualSupplyTemperature'
  - url: '/heatingCircuits/hc3/currentRoomSetpoint'
  - url: '/heatingCircuits/hc3/pumpModulation'
  - url: '/heatingCircuits/hc3/roomtemperature'
  - url: '/heatingCircuits/hc4/actualSupplyTemperature'
  - url: '/heatingCircuits/hc4/currentRoomSetpoint'
  - url: '/heatingCircuits/hc4/pumpModulation'
  - url: '/heatingCircuits/hc4/roomtemperature'
  - url: '/solarCircuits/sc1/actuatorStatus'
  - url: '/solarCircuits/sc1/collectorTemperature'
  - url: '/solarCircuits/sc1/dhwTankTemperature'
  - url: '/solarCircuits/sc1/pumpModulation'
  - url: '/solarCircuits/sc1/solarYield'
  - url: '/solarCircuits/sc1/status'
  - url: '/system/healthStatus'
  - url: '/system/sensors/temperatures/outdoor_t1'
  - url: '/system/sensors/temperatures/supply_t1'
